### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by Srikiranrao** [ros-industrial/easy_perception_deployment#13]
Hi ROS-I team,
I have set up a Realsense D435i  and have added the image topic “/camera/color/image_raw” to the “Deploy” GUI app.  While deploying the model, I faced a Docker error that it couldn’t find device drivers.
`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

![error](https://user-images.githubusercontent.com/43459203/113529711-c1273e00-95f6-11eb-8d14-2643fd396839.jpg)

**Comment by cardboardcode** [comment]
This issue is caused by **a missing installation of nvidia-docker**. 

Please run the following commands to install it:
```bash
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install -y nvidia-docker2
sudo systemctl restart docker
```
[Click here for Reference Docs](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit)

**Comment by Srikiranrao** [comment]
@cardboardcode 
After  installing  **nvidia-docker** packages. I faced the following issues as mentioned in the log.


![image](https://user-images.githubusercontent.com/43459203/113532970-49114600-95ff-11eb-937a-c889ebdfdf0f.png)

**Comment by cardboardcode** [comment]
The issue encounter is as follows:
```bash
[ ONNX Model ]: .x
[ Label List ]: ..t
```
This is caused by the user not selecting a valid ONNX model and Label List. Do check if the `.onnx` model file and '.txt' label list selected are still in their respective folder.

You can check it by looking at the `session_config.txt` file under the `easy_perception_deployment/data` folder.

**Comment by Srikiranrao** [comment]
I have two issues now:
1) Attached in the log below,  `[W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node` . It's running in CPU instead of GPU.
2) Attached in Image,  `No module named eps_msg`  when I subscribe to topic `ros2 topic echo /processor/epd_p3_output`. After building and sourcing the package 


**[- EPD Deployment Configurations -]
[ ONNX Model ] : ./data/model/maskrcnn-2021-04-01.onnx
[ Label List ] : ../data/label_list/name.txt
[ Input Image Topic ] : /camera/color/image_raw
Docker [ FOUND ]
epd-foxy-base:GPU  Docker Image [ FOUND ]
Do you wish to rebuild? [y/n]: y
Sourcing [ROS2]
Sourcing [Local Package/Workspace]
Building epd_msgs package
Starting >>> epd_msgs
Finished <<< epd_msgs [5.37s]                     

Summary: 1 package finished [5.48s]
Starting >>> easy_perception_deployment
[Processing: easy_perception_deployment]                             
--- stderr: easy_perception_deployment                                
** WARNING ** io features related to openni will be disabled
** WARNING ** io features related to openni2 will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
** WARNING ** visualization features related to openni will be disabled
** WARNING ** visualization features related to openni2 will be disabled
** WARNING ** apps features related to openni will be disabled
---
Finished <<< easy_perception_deployment [52.2s]

Summary: 1 package finished [52.4s]
  1 package had stderr output: easy_perception_deployment
Deploying package.
[INFO] [launch]: All log files can be found below /root/.ros/log/2021-04-05-06-04-24-245198-97750ad26a2b-2036
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [processor-1]: process started with pid [2038]
[processor-1] [-ONNX Model-]= maskrcnn-2021-04-01.onnx
[processor-1] 2021-04-05 06:04:24.782913688 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2029
[processor-1] 2021-04-05 06:04:24.782942892 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2244
[processor-1] 2021-04-05 06:04:24.782950342 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2245
[processor-1] 2021-04-05 06:04:24.782955076 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2046
[processor-1] 2021-04-05 06:04:24.782960394 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2043
[processor-1] 2021-04-05 06:04:24.782965032 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2035
[processor-1] 2021-04-05 06:04:24.782968461 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2038
[processor-1] 2021-04-05 06:04:24.782972972 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2032
[processor-1] 2021-04-05 06:04:24.782977526 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2037
[processor-1] 2021-04-05 06:04:24.782984479 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2039
[processor-1] 2021-04-05 06:04:24.782991953 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2060
[processor-1] 2021-04-05 06:04:24.782995618 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2061
[processor-1] 2021-04-05 06:04:24.782999946 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2063
[processor-1] 2021-04-05 06:04:24.783003697 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2064
[processor-1] 2021-04-05 06:04:24.783007298 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2065
[processor-1] 2021-04-05 06:04:24.783011551 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2066
[processor-1] 2021-04-05 06:04:24.783015084 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2067
[processor-1] 2021-04-05 06:04:24.783021802 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2056
[processor-1] 2021-04-05 06:04:24.783028363 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2052
[processor-1] 2021-04-05 06:04:24.783035917 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2073
[processor-1] 2021-04-05 06:04:24.783040795 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 549
[processor-1] 2021-04-05 06:04:24.783044737 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 811
[processor-1] 2021-04-05 06:04:24.783049382 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 546
[processor-1] 2021-04-05 06:04:24.783053430 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 810
[processor-1] 2021-04-05 06:04:24.783057612 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 812
[processor-1] 2021-04-05 06:04:24.783062167 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 794
[processor-1] 2021-04-05 06:04:24.783065590 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 795
[processor-1] 2021-04-05 06:04:24.783068933 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 796
[processor-1] 2021-04-05 06:04:24.783075795 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 779
[processor-1] 2021-04-05 06:04:24.783079688 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 780
[processor-1] 2021-04-05 06:04:24.783083352 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 781
[processor-1] 2021-04-05 06:04:24.783091843 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1731
[processor-1] 2021-04-05 06:04:24.783095469 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1946
[processor-1] 2021-04-05 06:04:24.783101403 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1947
[processor-1] 2021-04-05 06:04:24.783106017 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1748
[processor-1] 2021-04-05 06:04:24.783111298 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1745
[processor-1] 2021-04-05 06:04:24.783115813 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1737
[processor-1] 2021-04-05 06:04:24.783119240 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1740
[processor-1] 2021-04-05 06:04:24.783123848 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1734
[processor-1] 2021-04-05 06:04:24.783127329 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1739
[processor-1] 2021-04-05 06:04:24.783134013 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1741
[processor-1] 2021-04-05 06:04:24.783141323 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1762
[processor-1] 2021-04-05 06:04:24.783144779 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1763
[processor-1] 2021-04-05 06:04:24.783150030 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1765
[processor-1] 2021-04-05 06:04:24.783153459 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1766
[processor-1] 2021-04-05 06:04:24.783156808 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1767
[processor-1] 2021-04-05 06:04:24.783160254 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1768
[processor-1] 2021-04-05 06:04:24.783163625 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1769
[processor-1] 2021-04-05 06:04:24.783170045 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1758
[processor-1] 2021-04-05 06:04:24.783176659 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1754
[processor-1] 2021-04-05 06:04:24.783183759 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1775
[processor-1] 2021-04-05 06:04:24.783188314 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 543
[processor-1] 2021-04-05 06:04:24.783192366 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 754
[processor-1] 2021-04-05 06:04:24.783196959 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 540
[processor-1] 2021-04-05 06:04:24.783200496 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 753
[processor-1] 2021-04-05 06:04:24.783204558 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 755
[processor-1] 2021-04-05 06:04:24.783209539 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 737
[processor-1] 2021-04-05 06:04:24.783213639 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 738
[processor-1] 2021-04-05 06:04:24.783217745 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 739
[processor-1] 2021-04-05 06:04:24.783241746 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 722
[processor-1] 2021-04-05 06:04:24.783245492 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 723
[processor-1] 2021-04-05 06:04:24.783248965 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 724
[processor-1] 2021-04-05 06:04:24.783260075 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 412
[processor-1] 2021-04-05 06:04:24.783263825 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 413
[processor-1] 2021-04-05 06:04:24.783268271 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 400
[processor-1] 2021-04-05 06:04:24.783272908 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 402
[processor-1] 2021-04-05 06:04:24.783276386 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 403
[processor-1] 2021-04-05 06:04:24.783279798 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 404
[processor-1] 2021-04-05 06:04:24.783283268 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 406
[processor-1] 2021-04-05 06:04:24.783288279 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 393
[processor-1] 2021-04-05 06:04:24.783292712 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 395
[processor-1] 2021-04-05 06:04:24.783296151 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 396
[processor-1] 2021-04-05 06:04:24.783299711 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 397
[processor-1] 2021-04-05 06:04:24.783303213 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 405
[processor-1] 2021-04-05 06:04:24.783307369 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 407
[processor-1] 2021-04-05 06:04:24.783311650 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 415
[processor-1] 2021-04-05 06:04:24.783318258 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 416
[processor-1] 2021-04-05 06:04:24.783329110 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1433
[processor-1] 2021-04-05 06:04:24.783333320 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1648
[processor-1] 2021-04-05 06:04:24.783359537 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1649
[processor-1] 2021-04-05 06:04:24.783364488 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1450
[processor-1] 2021-04-05 06:04:24.783383455 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1447
[processor-1] 2021-04-05 06:04:24.783387947 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1439
[processor-1] 2021-04-05 06:04:24.783391346 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1442
[processor-1] 2021-04-05 06:04:24.783396197 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1436
[processor-1] 2021-04-05 06:04:24.783399862 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1441
[processor-1] 2021-04-05 06:04:24.783406576 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1443
[processor-1] 2021-04-05 06:04:24.783414282 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1464
[processor-1] 2021-04-05 06:04:24.783417789 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1465
[processor-1] 2021-04-05 06:04:24.783422178 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1467
[processor-1] 2021-04-05 06:04:24.783425702 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1468
[processor-1] 2021-04-05 06:04:24.783429272 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1469
[processor-1] 2021-04-05 06:04:24.783432894 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1470
[processor-1] 2021-04-05 06:04:24.783436400 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1471
[processor-1] 2021-04-05 06:04:24.783442845 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1460
[processor-1] 2021-04-05 06:04:24.783449877 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1456
[processor-1] 2021-04-05 06:04:24.783459248 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1477
[processor-1] 2021-04-05 06:04:24.783463836 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 537
[processor-1] 2021-04-05 06:04:24.783467960 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 697
[processor-1] 2021-04-05 06:04:24.783472638 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 534
[processor-1] 2021-04-05 06:04:24.783501228 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 696
[processor-1] 2021-04-05 06:04:24.783505743 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 698
[processor-1] 2021-04-05 06:04:24.783510539 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 680
[processor-1] 2021-04-05 06:04:24.783514614 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 681
[processor-1] 2021-04-05 06:04:24.783518325 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 682
[processor-1] 2021-04-05 06:04:24.783525620 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 665
[processor-1] 2021-04-05 06:04:24.783529436 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 666
[processor-1] 2021-04-05 06:04:24.783533062 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 667
[processor-1] 2021-04-05 06:04:24.783543561 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 446
[processor-1] 2021-04-05 06:04:24.783547378 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 447
[processor-1] 2021-04-05 06:04:24.783567005 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 434
[processor-1] 2021-04-05 06:04:24.783572069 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 436
[processor-1] 2021-04-05 06:04:24.783575522 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 437
[processor-1] 2021-04-05 06:04:24.783579062 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 438
[processor-1] 2021-04-05 06:04:24.783582477 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 440
[processor-1] 2021-04-05 06:04:24.783608421 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 427
[processor-1] 2021-04-05 06:04:24.783613358 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 429
[processor-1] 2021-04-05 06:04:24.783630986 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 430
[processor-1] 2021-04-05 06:04:24.783634511 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 431
[processor-1] 2021-04-05 06:04:24.783637901 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 439
[processor-1] 2021-04-05 06:04:24.783662460 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 441
[processor-1] 2021-04-05 06:04:24.783667039 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 449
[processor-1] 2021-04-05 06:04:24.783672099 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 450
[processor-1] 2021-04-05 06:04:24.783677611 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1135
[processor-1] 2021-04-05 06:04:24.783681683 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1350
[processor-1] 2021-04-05 06:04:24.783688390 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1351
[processor-1] 2021-04-05 06:04:24.783693395 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1152
[processor-1] 2021-04-05 06:04:24.783715812 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1149
[processor-1] 2021-04-05 06:04:24.783720307 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1141
[processor-1] 2021-04-05 06:04:24.783743496 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1144
[processor-1] 2021-04-05 06:04:24.783748183 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1138
[processor-1] 2021-04-05 06:04:24.783752098 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1143
[processor-1] 2021-04-05 06:04:24.783759429 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1145
[processor-1] 2021-04-05 06:04:24.783767433 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1166
[processor-1] 2021-04-05 06:04:24.783771362 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1167
[processor-1] 2021-04-05 06:04:24.783775978 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1169
[processor-1] 2021-04-05 06:04:24.783793042 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1170
[processor-1] 2021-04-05 06:04:24.783796740 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1171
[processor-1] 2021-04-05 06:04:24.783800676 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1172
[processor-1] 2021-04-05 06:04:24.783804293 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1173
[processor-1] 2021-04-05 06:04:24.783811050 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1162
[processor-1] 2021-04-05 06:04:24.783818162 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1158
[processor-1] 2021-04-05 06:04:24.783825691 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1179
[processor-1] 2021-04-05 06:04:24.783830257 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 531
[processor-1] 2021-04-05 06:04:24.783834531 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 640
[processor-1] 2021-04-05 06:04:24.783839027 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 528
[processor-1] 2021-04-05 06:04:24.783842724 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 639
[processor-1] 2021-04-05 06:04:24.783847007 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 641
[processor-1] 2021-04-05 06:04:24.783851803 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 623
[processor-1] 2021-04-05 06:04:24.783855303 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 624
[processor-1] 2021-04-05 06:04:24.783858702 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 625
[processor-1] 2021-04-05 06:04:24.783865102 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 608
[processor-1] 2021-04-05 06:04:24.783868572 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 609
[processor-1] 2021-04-05 06:04:24.783872239 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 610
[processor-1] 2021-04-05 06:04:24.783882769 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 480
[processor-1] 2021-04-05 06:04:24.783886566 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 481
[processor-1] 2021-04-05 06:04:24.783891198 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 468
[processor-1] 2021-04-05 06:04:24.783895983 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 470
[processor-1] 2021-04-05 06:04:24.783899342 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 471
[processor-1] 2021-04-05 06:04:24.783902860 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 472
[processor-1] 2021-04-05 06:04:24.783906328 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 474
[processor-1] 2021-04-05 06:04:24.783910840 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 461
[processor-1] 2021-04-05 06:04:24.783915583 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 463
[processor-1] 2021-04-05 06:04:24.783919034 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 464
[processor-1] 2021-04-05 06:04:24.783922581 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 465
[processor-1] 2021-04-05 06:04:24.783926234 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 473
[processor-1] 2021-04-05 06:04:24.783930552 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 475
[processor-1] 2021-04-05 06:04:24.783934842 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 483
[processor-1] 2021-04-05 06:04:24.783939330 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 484
[processor-1] 2021-04-05 06:04:24.783944844 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 837
[processor-1] 2021-04-05 06:04:24.783948369 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1052
[processor-1] 2021-04-05 06:04:24.783954348 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 1053
[processor-1] 2021-04-05 06:04:24.783958902 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 854
[processor-1] 2021-04-05 06:04:24.783964374 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 851
[processor-1] 2021-04-05 06:04:24.783968899 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 843
[processor-1] 2021-04-05 06:04:24.783972529 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 846
[processor-1] 2021-04-05 06:04:24.783977077 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 840
[processor-1] 2021-04-05 06:04:24.783980659 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 845
[processor-1] 2021-04-05 06:04:24.783987473 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 847
[processor-1] 2021-04-05 06:04:24.783994655 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 868
[processor-1] 2021-04-05 06:04:24.783998263 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 869
[processor-1] 2021-04-05 06:04:24.784002720 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 871
[processor-1] 2021-04-05 06:04:24.784006273 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 872
[processor-1] 2021-04-05 06:04:24.784009825 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 873
[processor-1] 2021-04-05 06:04:24.784013583 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 874
[processor-1] 2021-04-05 06:04:24.784017009 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 875
[processor-1] 2021-04-05 06:04:24.784023429 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 864
[processor-1] 2021-04-05 06:04:24.784030280 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 860
[processor-1] 2021-04-05 06:04:24.784037573 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 881
[processor-1] 2021-04-05 06:04:24.784046075 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 525
[processor-1] 2021-04-05 06:04:24.784049678 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 583
[processor-1] 2021-04-05 06:04:24.784054070 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 522
[processor-1] 2021-04-05 06:04:24.784057514 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 582
[processor-1] 2021-04-05 06:04:24.784061648 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 584
[processor-1] 2021-04-05 06:04:24.784066432 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 566
[processor-1] 2021-04-05 06:04:24.784069981 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 567
[processor-1] 2021-04-05 06:04:24.784077202 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 568
[processor-1] 2021-04-05 06:04:24.784083702 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 551
[processor-1] 2021-04-05 06:04:24.784087148 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 552
[processor-1] 2021-04-05 06:04:24.784090478 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 553
[processor-1] 2021-04-05 06:04:24.784099670 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2329
[processor-1] 2021-04-05 06:04:24.784103273 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2330
[processor-1] 2021-04-05 06:04:24.784106850 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2331
[processor-1] 2021-04-05 06:04:24.784110346 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2332
[processor-1] 2021-04-05 06:04:24.784114024 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2333
[processor-1] 2021-04-05 06:04:24.784120596 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2581
[processor-1] 2021-04-05 06:04:24.784128077 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2585
[processor-1] 2021-04-05 06:04:24.784132565 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2578
[processor-1] 2021-04-05 06:04:24.784136014 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2584
[processor-1] 2021-04-05 06:04:24.784140394 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2575
[processor-1] 2021-04-05 06:04:24.784143776 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2583
[processor-1] 2021-04-05 06:04:24.784148106 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2572
[processor-1] 2021-04-05 06:04:24.784151947 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2582
[processor-1] 2021-04-05 06:04:24.784157358 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2586
[processor-1] 2021-04-05 06:04:24.784163569 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2554
[processor-1] 2021-04-05 06:04:24.784167056 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2558
[processor-1] 2021-04-05 06:04:24.784172043 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2551
[processor-1] 2021-04-05 06:04:24.784175597 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2557
[processor-1] 2021-04-05 06:04:24.784179744 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2548
[processor-1] 2021-04-05 06:04:24.784183461 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2556
[processor-1] 2021-04-05 06:04:24.784188039 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2545
[processor-1] 2021-04-05 06:04:24.784191634 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2555
[processor-1] 2021-04-05 06:04:24.784197110 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2559
[processor-1] 2021-04-05 06:04:24.784202579 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2527
[processor-1] 2021-04-05 06:04:24.784206137 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2531
[processor-1] 2021-04-05 06:04:24.784210360 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2524
[processor-1] 2021-04-05 06:04:24.784213912 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2530
[processor-1] 2021-04-05 06:04:24.784218107 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2521
[processor-1] 2021-04-05 06:04:24.784221546 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2529
[processor-1] 2021-04-05 06:04:24.784226255 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2518
[processor-1] 2021-04-05 06:04:24.784229738 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2528
[processor-1] 2021-04-05 06:04:24.784235044 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2532
[processor-1] 2021-04-05 06:04:24.784240698 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2500
[processor-1] 2021-04-05 06:04:24.784244215 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2504
[processor-1] 2021-04-05 06:04:24.784248464 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2497
[processor-1] 2021-04-05 06:04:24.784252063 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2503
[processor-1] 2021-04-05 06:04:24.784256368 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2494
[processor-1] 2021-04-05 06:04:24.784259726 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2502
[processor-1] 2021-04-05 06:04:24.784264059 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2491
[processor-1] 2021-04-05 06:04:24.784267644 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2501
[processor-1] 2021-04-05 06:04:24.784273121 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2505
[processor-1] 2021-04-05 06:04:24.784279089 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2475
[processor-1] 2021-04-05 06:04:24.784282576 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2479
[processor-1] 2021-04-05 06:04:24.784287476 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2472
[processor-1] 2021-04-05 06:04:24.784291066 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2478
[processor-1] 2021-04-05 06:04:24.784295369 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2469
[processor-1] 2021-04-05 06:04:24.784298879 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2477
[processor-1] 2021-04-05 06:04:24.784303457 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2466
[processor-1] 2021-04-05 06:04:24.784307096 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2476
[processor-1] 2021-04-05 06:04:24.784313025 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2480
[processor-1] 2021-04-05 06:04:24.784318841 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2787
[processor-1] 2021-04-05 06:04:24.784322460 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2824
[processor-1] 2021-04-05 06:04:24.784326967 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2825
[processor-1] 2021-04-05 06:04:24.784332409 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2820
[processor-1] 2021-04-05 06:04:24.784336228 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2821
[processor-1] 2021-04-05 06:04:24.784340592 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2822
[processor-1] 2021-04-05 06:04:24.784346979 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2966
[processor-1] 2021-04-05 06:04:24.784355253 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2967
[processor-1] 2021-04-05 06:04:24.784359008 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2968
[processor-1] 2021-04-05 06:04:24.784362493 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2969
[processor-1] 2021-04-05 06:04:24.784365940 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 2970
[processor-1] 2021-04-05 06:04:24.784373008 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3222
[processor-1] 2021-04-05 06:04:24.784376450 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3226
[processor-1] 2021-04-05 06:04:24.784380894 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3219
[processor-1] 2021-04-05 06:04:24.784384587 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3225
[processor-1] 2021-04-05 06:04:24.784389070 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3216
[processor-1] 2021-04-05 06:04:24.784392473 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3224
[processor-1] 2021-04-05 06:04:24.784396863 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3213
[processor-1] 2021-04-05 06:04:24.784400507 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3223
[processor-1] 2021-04-05 06:04:24.784405876 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3227
[processor-1] 2021-04-05 06:04:24.784411079 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3195
[processor-1] 2021-04-05 06:04:24.784414636 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3199
[processor-1] 2021-04-05 06:04:24.784418917 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3192
[processor-1] 2021-04-05 06:04:24.784422372 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3198
[processor-1] 2021-04-05 06:04:24.784426461 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3189
[processor-1] 2021-04-05 06:04:24.784430027 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3197
[processor-1] 2021-04-05 06:04:24.784434544 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3186
[processor-1] 2021-04-05 06:04:24.784438018 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3196
[processor-1] 2021-04-05 06:04:24.784443789 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3200
[processor-1] 2021-04-05 06:04:24.784449250 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3168
[processor-1] 2021-04-05 06:04:24.784452805 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3172
[processor-1] 2021-04-05 06:04:24.784457062 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3165
[processor-1] 2021-04-05 06:04:24.784460522 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3171
[processor-1] 2021-04-05 06:04:24.784464934 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3162
[processor-1] 2021-04-05 06:04:24.784468403 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3170
[processor-1] 2021-04-05 06:04:24.784472779 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3159
[processor-1] 2021-04-05 06:04:24.784476302 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3169
[processor-1] 2021-04-05 06:04:24.784481552 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3173
[processor-1] 2021-04-05 06:04:24.784486906 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3141
[processor-1] 2021-04-05 06:04:24.784490637 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3145
[processor-1] 2021-04-05 06:04:24.784494827 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3138
[processor-1] 2021-04-05 06:04:24.784498539 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3144
[processor-1] 2021-04-05 06:04:24.784502903 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3135
[processor-1] 2021-04-05 06:04:24.784506363 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3143
[processor-1] 2021-04-05 06:04:24.784510723 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3132
[processor-1] 2021-04-05 06:04:24.784514224 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3142
[processor-1] 2021-04-05 06:04:24.784519448 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3146
[processor-1] 2021-04-05 06:04:24.784524936 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3116
[processor-1] 2021-04-05 06:04:24.784528417 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3120
[processor-1] 2021-04-05 06:04:24.784532979 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3113
[processor-1] 2021-04-05 06:04:24.784536745 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3119
[processor-1] 2021-04-05 06:04:24.784540961 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3110
[processor-1] 2021-04-05 06:04:24.784544312 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3118
[processor-1] 2021-04-05 06:04:24.784549186 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3107
[processor-1] 2021-04-05 06:04:24.784552671 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3117
[processor-1] 2021-04-05 06:04:24.784558075 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3121
[processor-1] 2021-04-05 06:04:24.784563442 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3278
[processor-1] 2021-04-05 06:04:24.784568275 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3258
[processor-1] 2021-04-05 06:04:24.784571679 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3259
[processor-1] 2021-04-05 06:04:24.784575259 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3260
[processor-1] 2021-04-05 06:04:24.784583846 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3271
[processor-1] 2021-04-05 06:04:24.784587629 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3273
[processor-1] 2021-04-05 06:04:24.784591824 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3268
[processor-1] 2021-04-05 06:04:24.784595443 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3272
[processor-1] 2021-04-05 06:04:24.784600475 [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: 3274
[processor-1] [-Precision Level-]= 3
[processor-1] [-Label List-]= ./data/label_list/name.txt
[processor-1] [-Use Case-]= EPD::LOCALISATION_MODE
[processor-1] [- Input RGB Image Topic -]= /camera/color/image_raw
[processor-1] [- Input Depth Image Topic -]= /camera/aligned_depth_to_color/image_raw
[processor-1] [- Camera Info Topic -]= /camera/color/camera_info`**

![image](https://user-images.githubusercontent.com/43459203/113543587-402d6e00-9619-11eb-8a2a-a34fdead4ca0.png)

**Comment by cardboardcode** [comment]
> I have two issues now:
>
>    Attached in the log below, [W:onnxruntime:Ort, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU >execution for node . It's running in CPU instead of GPU.
>    Attached in Image, No module named eps_msg when I subscribe to topic ros2 topic echo /processor/epd_p3_output. After building and sourcing the package
@Srikiranrao 

The first issue is expected so no need to be alarmed by it. Some parts of the model is expected to fallback to CPU due to **onnxruntime**'s limitations. There is still parts of the model instantiated in the GPU that still achieves enhancement in performance.

The second issue is caused by the terminal you are running the command: 
```bash
ros2 topic echo /processor/epd_p3_output
```
This can be easily resolved by running the command below in the same terminal:
```bash
# Ensure you are in the easy_perception_deployment ROS2 package folder.
source ../epd_msgs/install/setup.bash
ros2 topic echo /processor/epd_p3_output
```

**Comment by Srikiranrao** [comment]
Hi @cardboardcode 
When subscribing to the topic `ros2 topic echo /processor/epd_p3_output` I couldn't view any output and the  `ShowImage` window is getting stuck. May I know how to resolve this?

![image](https://user-images.githubusercontent.com/43459203/113562151-323b1580-9638-11eb-99c8-58f822a305de.png)

**Comment by cardboardcode** [comment]
>Hi @cardboardcode
>When subscribing to the topic ros2 topic echo /processor/epd_p3_output I couldn't view any output. May I know how to resolve this? 

It would seem that the original issue in this thread has been resolved. Please open up a new issue for the one above.
This new issue is more ambiguous and more information (Eg. Is your camera driver ROS2 driver package running? What is the output of **easy_percerption_deployment** ROS2 package when it has **successfully** connected to the driver package?) is required. 

Closing issue.

**Comment by Srikiranrao** [comment]
@cardboardcode  Thanks for your support. The above issue was resolved.
